### ISSUE TITLE
Add ability to copy files from the VM

### ISSUE THREAD

**Issue by isbadawi** [invernizzi/vagrant-scp#1]
Maybe a flag to flip the source and destination? Or an optional prefix like `vm:` on one of the files?

**Comment by invernizzi** [comment]
Hi Ismail,
I've added support for this. All these commands now work:

``` bash
vagrant scp test.txt /home/vagrant/hello.txt   # copies a file to the default VM
vagrant scp test.txt  my_vm:/home/vagrant/hello.txt  # copies a file to the 'my_vm' VM
vagrant scp my_vm:/home/vagrant/hello.txt test.txt  # copies the file back out
```

Let me know if this works for you

You need to update the plugin (vagrant plugin update vagrant-scp) to get this

**Comment by isbadawi** [comment]
Yep, this works, thanks!
