### ISSUE TITLE
SCP did not finish successfully 

### ISSUE THREAD

**Issue by oefada** [invernizzi/vagrant-scp#12]
i'm getting the following message back.

{message}/opt/vagrant/embedded/gems/gems/net-scp-1.1.2/lib/net/scp.rb:359:in `block (3 levels) in start_command': SCP did not finish successfully (1) (Net::SCP::Error)
    from /Users/xadmin/.vagrant.d/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:591:in`call'
    from /Users/xadmin/.vagrant.d/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:591:in `do_close'
    from /Users/xadmin/.vagrant.d/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:587:in`channel_close'
    from /Users/xadmin/.vagrant.d/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:466:in `dispatch_incoming_packets'
    from /Users/xadmin/.vagrant.d/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:222:in`preprocess'
    from /Users/xadmin/.vagrant.d/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:206:in `process'
    from /Users/xadmin/.vagrant.d/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in`block in loop'
    from /Users/xadmin/.vagrant.d/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
    from /Users/xadmin/.vagrant.d/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in`loop'
    from /Users/xadmin/.vagrant.d/gems/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:119:in `close'
    from /opt/vagrant/embedded/gems/gems/net-scp-1.1.2/lib/net/scp.rb:205:in`ensure in start'
    from /opt/vagrant/embedded/gems/gems/net-scp-1.1.2/lib/net/scp.rb:205:in `start'
    from /opt/vagrant/embedded/gems/gems/net-scp-1.1.2/lib/net/scp.rb:221:in`upload!'
    from /Users/xadmin/.vagrant.d/gems/gems/vagrant-scp-0.5.3/lib/vagrant/scp/commands/scp.rb:21:in `block in execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:226:in`block in with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:220:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:220:in`with_target_vms'
    from /Users/xadmin/.vagrant.d/gems/gems/vagrant-scp-0.5.3/lib/vagrant/scp/commands/scp.rb:17:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in`execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'

**Comment by invernizzi** [comment]
Thanks for reporting this. Version 0.5.4 fixes this issue.
