### ISSUE TITLE
Please allow to use Vagrant IDs as well as name

### ISSUE THREAD

**Issue by Miserlou** [invernizzi/vagrant-scp#13]
Most plugins allow this, it slightly tripped me when I realized this plugin required name and not ID.

Very useful plugin for me today, thank you!

**Comment by invernizzi** [comment]
Hi Rich, great profile picture!
You can use the Vagrant ID in place of the machine name. I quickly tested it on my machine, and it seems to work. Please confirm, and I'll update the `README.md`
