### ISSUE TITLE
Doesn't support source paths with embedded spaces

### ISSUE THREAD

**Issue by therealcmj** [invernizzi/vagrant-scp#14]
$ vagrant scp ~/Temporary\ Files/file.7z oim1admin:~
Warning: Permanently added '[127.0.0.1]:2200' (RSA) to the list of known hosts.
/Users/cmj/Temporary: No such file or directory
Files/file.7z: No such file or directory

**Comment by invernizzi** [comment]
Thanks! Fix added in version 0.5.5

**Comment by therealcmj** [comment]
Thanks!
