### ISSUE TITLE
Release 0.5.4 broke backward compatibility

### ISSUE THREAD

**Issue by mkuzmin** [invernizzi/vagrant-scp#15]
Native `scp` tool and `Net::SCP` gem are not 100% compatible.

For example they work with subdirectories in different ways.
In version 0.4 a command `vagrant scp teamcity:/usr/local/teamcity/logs build/server-logs/` downloaded files right into `server-logs/` directory.
Version 0.5 started creating a subdirectory, and put files into `server-logs/logs/`.

That change broke my build scripts, but that was fine - it was a feature release.
But version 0.5.4 turned the logic back, and my builds are broken again.

There is nothing to fix, and you can close this issue right away. But in future please do not introduce such changes in bugfix releases.

**Comment by invernizzi** [comment]
Sorry for the breakage, Michael. Unfortunately, whereas using `Net::SCP` is more elegant, it is considerably slower that `scp`. I'll stick with `scp`, and I'll make sure to use major releases.
