### ISSUE TITLE
README: Suggest mentioning default VM name is "default"

### ISSUE THREAD

**Issue by davidfstr** [invernizzi/vagrant-scp#16]
To copy files out of a VM with "vagrant scp" it is necessary to explicitly specify the VM name. However it's not clear what the default VM name is.

After poking around a while I determined the default VM is just called "default". (As opposed to something that "vagrant box list" indicates.)

Suggest extending the README with this information for the hurried dev. :-)

```
vagrant scp default:~/magic.txt magic.txt
```

**Comment by CharlesCarnell** [comment]
Experienced the very same, I'd also recommend adding this to the README.

**Comment by invernizzi** [comment]
The VM name is optional (square brackets). In your example:
`vagrant scp  :~/magic.txt magic.txt`
works fine.
I'll add a clarification to the README

**Comment by invernizzi** [comment]
Done. Thanks for reporting this!
