### ISSUE TITLE
[vm_name] is mandatory

### ISSUE THREAD

**Issue by cscetbon** [invernizzi/vagrant-scp#17]
Hey,

The help says we can use 
`vagrant scp <local_path> [vm_name]:<remote_path>`

however if I don't provide the vm_name I get  : 
`The working directory for Vagrant doesn't exist!`

[vm_name] should be an optional argument, right ? otherwise I would replace it by `<vm_name>` to emphasize that it is a mandatory argument. I'm wondering if you didn't mean : 
`vagrant scp <local_path> <vm_name>:[remote_path]`

**Comment by invernizzi** [comment]
Thanks! That's a regression: the help is correct. Fix released in version 0.5.6
