### ISSUE TITLE
Missing to support ssh option 'ProxyCommand'

### ISSUE THREAD

**Issue by prabhatmaurya** [invernizzi/vagrant-scp#18]
Hi, 

First of all thanks for this plugin. I added a line to support 'ProxyCommand' in my local plugin. May be you can add this patch in original code.

Scenario:- In our local openstack environment , port 22 is block by default from user environment. We have to login to step server to login in Openstack instances.

default vagrant ssh support feature to add ssh proxy via setting 'config.ssh.proxy_command'   but this scp plugin is not using that option.

To fix this issue I added a line in [vagrant-scp]/lib/vagrant/scp/commands/scp.rb file.

PATCH:-

<pre>

$ git diff
diff --git a/lib/vagrant/scp/commands/scp.rb b/lib/vagrant/scp/commands/scp.rb
index 0620ad8..fdca776 100644
--- a/lib/vagrant/scp/commands/scp.rb
+++ b/lib/vagrant/scp/commands/scp.rb
@@ -30,6 +30,7 @@ module VagrantPlugins
               "-o StrictHostKeyChecking=no",
               "-o UserKnownHostsFile=/dev/null",
               "-o port=#{@ssh_info[:port]}",
+              "-o ProxyCommand='#{@ssh_info[:proxy_command]}'",
               "-i '#{@ssh_info[:private_key_path][0]}'",
               source,
               target

</pre>

**Comment by invernizzi** [comment]
Thanks for the patch! I've tweaked a tiny bit, since it was breaking the case where no `ProxyCommand` is given.
Released in version 0.5.7
