### ISSUE TITLE
Can't specify the remote user

### ISSUE THREAD

**Issue by marko-p** [invernizzi/vagrant-scp#22]
How do I scp files on the remote machine that are not accessible by the vagrant user?

**Comment by daks** [comment]
Same question here, is there anyway to 'sudo' the copy?

**Comment by tangrufus** [comment]
Try [vagrant-sudo-rsync](https://github.com/TypistTech/vagrant-sudo-rsync)

It's equivalent to `$ rsync --rsh=<automatically determined> --rsync-path='sudo rsync' [OPTION] SRC DEST`, allowing you to act as `sudo`

**Comment by MarcinOrlowski** [comment]
This plugin currently acts as `vagrant` user. Perhaps mentioned vagrant-sudo-rsync may be better choice when you need to put your files directly to location not writable by `vagrant`.
