### ISSUE TITLE
Allow default destination file name to "."

### ISSUE THREAD

**Issue by amosshapira** [invernizzi/vagrant-scp#26]
In normal `scp`, if the destination contains only a hostname then the default destination path is "`.`". It would be nice to have the same with `vagrant-scp`.

i.e.
```
vagrant scp ~/.bashrc vagrant-box:
```
Would behave the same as:
```
vagrant scp ~/.bashrc vagrant-box:.
```
i.e. actually the same as:
```
vagrant scp ~/.bashrc vagrant-box:.bashrc
```

**Comment by MarcinOrlowski** [comment]
This PR: #31 addresses this issue.

**Comment by amosshapira** [comment]
Thanks!
