### ISSUE TITLE
Plugin failes installation

### ISSUE THREAD

**Issue by digihash** [invernizzi/vagrant-scp#27]
After installing the plugin by first creating the gem file: $ gem build vagrant-scp.gemspec
And then installing it: $ vagrant Plugin install <path-to-vagrant-scp-dir>/vagrant-scp-0.5.6.gem

I wanted to build my vagrant vm with: $ vagrant up
But then I encountered the following issue. 
---------------------------------------
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is shown below. 

cannot load such file - - vagrant-scp
---------------------------------------

Also the vagrant score command doesn't work, same error. 

When I uninstall the vagrant-scp plugin, everything works as expected again.

**Comment by MarcinOrlowski** [comment]
This is quite old issue report. I am closing it now. Please reopen if you are still experiencing this problem with recent Vagrant version
