### ISSUE TITLE
Can't copy to /var/www directory

### ISSUE THREAD

**Issue by mehrdad-shokri** [invernizzi/vagrant-scp#30]
Hey, thanks for providing this plugin.  
When trying to scp a directory from host machine to guest vm I get error ``Permission denied``.  
I can confirm that, I can copy files to another directory like ``tmp`` but not ``/var/www``  
Do you know any reason for this behaviour?  
Also how to prevent this permission error from happening?  
Host machine is Windows 10 and vagrant is run on VirtualBox

**Comment by MarcinOrlowski** [comment]
At the moment you are acting as `vagrant` user, not `root` therefore you do not have write access to `/var/www/` by default. You need to scp to other location and then `vagrant ssh` + `sudo -s` and do the move the files. This is perhaps not what you wish but this is how it works now.
