### ISSUE TITLE
The plugin "vagrant-scp" could not be found

### ISSUE THREAD

**Issue by rodsimpson** [invernizzi/vagrant-scp#4]
After installing, I get this error:
vagrant up

The plugin "vagrant-scp" could not be found. Please make sure that it is
properly installed via `vagrant plugin`. Note that plugins made for
Vagrant 1.0.x are not compatible with 1.1+ and this error will likely
continue to show when you use `plugin install` with a 1.0.x plugin.

vagrant --version
Vagrant 1.4.3

The readme file doesn't say what version of vagrant is supported.

**Comment by invernizzi** [comment]
Hi Rod,
I support the current version of Vagrant, 1.7. I've added the note in the readme. Thanks for letting me know!
